name: Build and test Go

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.5'

      - name: Install dependencies
        run: |
	  go get .
	  go get github.com/gorilla/securecookie@v1.1.1
	  go get github.com/gorilla/sessions@1.2.1
	  go get github.com/lib/pq@v1.10.9
	  go get golang.org/x/crypto@0.11.0

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
